// Generated by CoffeeScript 1.11.1
(function() {
  var age, ages, bitlist, child, copy, countdown, courses, end, evens, foods, kids, lyrics, middle, num, numbers, ref, singers, song, start, x, yearsOld;

  song = ["1", "2", "3", "4", "5", "6", "7"];

  singers = {
    Jagger: "Rock",
    Elvis: "Roll"
  };

  bitlist = [1, 2, 1, 2, 2, 2, 3, 2, 1];

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Ida",
      age: 9
    }
  };

  courses = ['greens', 'caviar', 'truffles', 'roast', 'cake'];

  foods = ['broccoli', 'spinach', 'chocolate'];

  countdown = (function() {
    var i, results;
    results = [];
    for (num = i = 10; i >= 1; num = --i) {
      results.push(num);
    }
    return results;
  })();

  console.log(countdown);

  evens = (function() {
    var i, results;
    results = [];
    for (x = i = 0; i <= 10; x = i += 2) {
      results.push(x);
    }
    return results;
  })();

  yearsOld = {
    max: 10,
    ida: 9,
    tim: 11
  };

  ages = (function() {
    var results;
    results = [];
    for (child in yearsOld) {
      age = yearsOld[child];
      results.push(child + " is " + age);
    }
    return results;
  })();

  if (this.studyingEconomics) {
    while (supply > demand) {
      buy();
    }
    while (!(supply > demand)) {
      sell();
    }
  }

  num = 6;

  lyrics = (function() {
    var results;
    results = [];
    while (num -= 1) {
      results.push(num + " little monkeys, jumping on the bed. One fell out and bumped his head.");
    }
    return results;
  })();

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  start = numbers.slice(0, 3);

  console.log(start);

  middle = numbers.slice(3, -3);

  console.log(middle);

  end = numbers.slice(-2);

  console.log(end);

  copy = numbers.slice(0);

  console.log(copy);

  numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  [].splice.apply(numbers, [3, 4].concat(ref = [-3, -4, -5, -6])), ref;

  console.log(numbers);

}).call(this);
