// Generated by CoffeeScript 1.11.1
(function() {
  var age, ages, bitlist, child, countdown, courses, dish, evens, food, foods, i, j, k, kids, l, len, len1, len2, num, ref, singers, song, x, yearsOld;

  song = ["1", "2", "3", "4", "5", "6", "7"];

  singers = {
    Jagger: "Rock",
    Elvis: "Roll"
  };

  bitlist = [1, 2, 1, 2, 2, 2, 3, 2, 1];

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Ida",
      age: 9
    }
  };

  ref = ['toast', 'cheese', 'wine'];
  for (j = 0, len = ref.length; j < len; j++) {
    food = ref[j];
    eat(food);
  }

  courses = ['greens', 'caviar', 'truffles', 'roast', 'cake'];

  for (i = k = 0, len1 = courses.length; k < len1; i = ++k) {
    dish = courses[i];
    menu(i + 1, dish);
  }

  foods = ['broccoli', 'spinach', 'chocolate'];

  for (l = 0, len2 = foods.length; l < len2; l++) {
    food = foods[l];
    if (food !== 'chocolate') {
      eat(food);
    }
  }

  countdown = (function() {
    var m, results;
    results = [];
    for (num = m = 10; m >= 1; num = --m) {
      results.push(num);
    }
    return results;
  })();

  evens = (function() {
    var m, results;
    results = [];
    for (x = m = 0; m <= 10; x = m += 2) {
      results.push(x);
    }
    return results;
  })();

  yearsOld = {
    max: 10,
    ida: 9,
    tim: 11
  };

  ages = (function() {
    var results;
    results = [];
    for (child in yearsOld) {
      age = yearsOld[child];
      results.push(child + " is " + age);
    }
    return results;
  })();

}).call(this);
