// Generated by CoffeeScript 1.11.1
(function() {
  var city, forecast, futurists, name, ref, ref1, ref2, ref3, street, temp, theBait, theSwitch, weatherReport;

  theBait = 1000;

  theSwitch = 0;

  ref = [theSwitch, theBait], theBait = ref[0], theSwitch = ref[1];

  weatherReport = function(location) {
    return [location, 72, "Mostly Sunny"];
  };

  ref1 = weatherReport("Berkeley, CA"), city = ref1[0], temp = ref1[1], forecast = ref1[2];

  console.log(city);

  console.log(temp);

  console.log(forecast);

  futurists = {
    sculptor: "Umberto Boccioni",
    painter: "Vladimir Burliuk",
    poet: {
      name: "F.T. Marinetti",
      address: ["Via Roma 42R", "Bellagio, Italy 22021"]
    }
  };

  ref2 = futurists.poet, name = ref2.name, (ref3 = ref2.address, street = ref3[0], city = ref3[1]);

}).call(this);


// 解构赋值还可以跟 splats 搭配使用.

tag = "<impossible>"

[open, contents..., close] = tag.split("")


// 展开式(expansion)可以用于获取数组结尾的元素, 而不需要对中间过程的数据进行赋值. 它也可以用在函数参数的列表上.
text = "Every literary critic believes he will outwit history and have the last word"

[first, ..., last] = text.split " "

// 解构赋值也可以用在 class 的构造器上, 从构造器配置对象赋值到示例属性上.
class Person
  constructor: (options) -> 
    {@name, @age, @height} = options

tim = new Person age: 4