// Generated by CoffeeScript 1.11.1
(function() {
  var cube, fill, square;

  square = function(x) {
    return x * x;
  };

  cube = function(x) {
    return square(x) * x;
  };

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "filling the " + container + " with " + liquid;
  };

  this.customer = customer;

  this.cart = cart;

  $('.shopping_cart').bind('click', (function(_this) {
    return function(event) {
      return _this.customer.purchase(_this.cart);
    };
  })(this));

}).call(this);
