// Generated by CoffeeScript 1.11.1
(function() {
  var changeNums, inner, outer;

  outer = -1;

  changeNums = function() {
    var inner;
    inner = 1;
    return outer = 10;
  };

  inner = changeNums();

}).call(this);
