// Generated by CoffeeScript 1.11.1
(function() {
  var OPERATOR, author, cholesterol, error, grade, healthy, mobyDick, quote, score, sentence;

  switch (day) {
    case "Mon":
      go(work);
      break;
    case "Tue":
      go(relax);
      break;
    case "Thu":
      go(iceFishing);
      break;
    case "Fri":
    case "Sat":
      if (day === bingoDay) {
        go(bingo);
        go(dancing);
      }
      break;
    case "Sun":
      go(church);
      break;
    default:
      go(work);
  }

  score = 76;

  grade = (function() {
    switch (false) {
      case !(score < 60):
        return 'F';
      case !(score < 70):
        return 'D';
      case !(score < 80):
        return 'C';
      case !(score < 90):
        return 'B';
      default:
        return 'A';
    }
  })();

  try {
    allHellBreaksLoose();
    catsAndDogsLivingTogether();
  } catch (error1) {
    error = error1;
    print(error);
  } finally {
    cleanUp();
  }

  cholesterol = 127;

  healthy = (200 > cholesterol && cholesterol > 60);

  author = "Wittgenstein";

  quote = "A picture is a fact. -- " + author;

  sentence = (22 / 7) + " is a decent approximation of π";

  mobyDick = "Call me Ishmael. Some years ago -- never mind how long precisely -- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world...";


  /*
  SkinnyMochaHalfCaffScript Compiler v1.0
  Released under the MIT License
   */

  OPERATOR = /^(?:[-=]>|[-+*\/%<>&|^!?=]=|>>>=?|([-+:])\1|([&|<>])\2=?|\?\.|\.{2,3})/;

}).call(this);
